name: Practice projecet

on:
    issues:
      types: [opened]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: get message
        run: |
            echo "${{ toJson(github.event.issue.body) }}"
            
 

      
