name: Practice project

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm test

  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: use artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

      - name: Deploy application
        run: |
          echo "Deploying application..."
          ls -al
